
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bombdismantlement.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bombdismantlement(object):
    def setupUi(self, Bombdismantlement):
        Bombdismantlement.setObjectName("Bombdismantlement")
        Bombdismantlement.setMinimumSize(QtCore.QSize(317, 185))
        Bombdismantlement.setMaximumSize(QtCore.QSize(317, 185))
        self.centralwidget = QtWidgets.QWidget(Bombdismantlement)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.time = QtWidgets.QLCDNumber(self.centralwidget)
        self.time.setObjectName("time")
        self.verticalLayout.addWidget(self.time)
        self.password = QtWidgets.QLCDNumber(self.centralwidget)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 0, 0, 1, 1)
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 0, 1, 1, 1)
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 0, 2, 1, 1)
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 1, 0, 1, 1)
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 1, 1, 1, 1)
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 1, 2, 1, 1)
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 2, 0, 1, 1)
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 2, 1, 1, 1)
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 2, 2, 1, 1)
        self.disbomb = QtWidgets.QPushButton(self.centralwidget)
        self.disbomb.setObjectName("disbomb")
        self.gridLayout.addWidget(self.disbomb, 3, 0, 1, 1)
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 3, 1, 1, 1)
        self.set_bomb = QtWidgets.QPushButton(self.centralwidget)
        self.set_bomb.setObjectName("set_bomb")
        self.gridLayout.addWidget(self.set_bomb, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        Bombdismantlement.setCentralWidget(self.centralwidget)

        self.retranslateUi(Bombdismantlement)
        QtCore.QMetaObject.connectSlotsByName(Bombdismantlement)

    def retranslateUi(self, Bombdismantlement):
        _translate = QtCore.QCoreApplication.translate
        Bombdismantlement.setWindowTitle(_translate("Bombdismantlement", "bombdismantlement"))
        self.one.setText(_translate("Bombdismantlement", "1"))
        self.two.setText(_translate("Bombdismantlement", "2"))
        self.three.setText(_translate("Bombdismantlement", "3"))
        self.four.setText(_translate("Bombdismantlement", "4"))
        self.five.setText(_translate("Bombdismantlement", "5"))
        self.six.setText(_translate("Bombdismantlement", "6"))
        self.seven.setText(_translate("Bombdismantlement", "7"))
        self.eight.setText(_translate("Bombdismantlement", "8"))
        self.nine.setText(_translate("Bombdismantlement", "9"))
        self.disbomb.setText(_translate("Bombdismantlement", "拆弹"))
        self.zero.setText(_translate("Bombdismantlement", "0"))
        self.set_bomb.setText(_translate("Bombdismantlement", "设置密码"))
